[package]
name = "learning-rust-zeromq-pubsub"
version = "0.1.0"
authors = ["Roger Russel <roger.russel@dafiti.com.br>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zmq = "0.9"